import os
import sqlite3
import pandas as pd

# 1. READ ABC FILES FROM MULTIPLE FOLDERS

# 2. PARSE AND STORE TUNES INTO A LIST OF DICTIONARIES

# 3. STORE THE DATA IN AN SQL DATABASE

# 4. LOAD DATA INTO PANDAS FOR ANALYSIS

# 5. CREATE A SIMPLE USER INTERFACE FOR QUERYING

# 6. MAINTAIN PROPER VERSION CONTROL WITH GIT/GITHUB
